CREATE TABLE INVESTMENTS (
    permalink VARCHAR(255) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    homepage_url VARCHAR(255),
    category_list TEXT,
    market VARCHAR(100),
    funding_total_usd NUMERIC(15,2),
    status VARCHAR(50),
    country_code VARCHAR(10),
    state_code VARCHAR(10),
    region VARCHAR(100),
    city VARCHAR(100),
    funding_rounds INTEGER,
    founded_at DATE,
    founded_month VARCHAR(7),
    founded_quarter VARCHAR(7),
    founded_year INTEGER,
    first_funding_at DATE,
    last_funding_at DATE,
    seed NUMERIC(15,2),
    venture NUMERIC(15,2),
    equity_crowdfunding NUMERIC(15,2),
    undisclosed NUMERIC(15,2),
    convertible_note NUMERIC(15,2),
    debt_financing NUMERIC(15,2),
    angel NUMERIC(15,2),
    grants NUMERIC(15,2),
    private_equity NUMERIC(15,2),
    post_ipo_equity NUMERIC(15,2),
    post_ipo_debt NUMERIC(15,2),
    secondary_market NUMERIC(15,2),
    product_crowdfunding NUMERIC(15,2),
    round_A NUMERIC(15,2),
    round_B NUMERIC(15,2),
    round_C NUMERIC(15,2),
    round_D NUMERIC(15,2),
    round_E NUMERIC(15,2),
    round_F NUMERIC(15,2),
    round_G NUMERIC(15,2),
    round_H NUMERIC(15,2)
);